# Site settings
title: Carmap
email: hello@carmap.pl
url: https://carmap.pl
description: "Carmap is an innovative startup that aims to change the way we move around cities.."
keywords: "carsharing, scootersharing, carmap urban mobility, startup"
skills: "Innovation in Urban Mobility"
meta_author: Carmap

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3ec95e #80B3FF
  primary-rgb: "62,201,94" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Carmap

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
